version: '2'
services:
  web:
    image: kevloves/kevloves.dev:development
    build:
      context: ./
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"