version: '2'
services:
  web:
    image: kevloves/kevloves.dev:production
    build:
      context: ./
      dockerfile: Dockerfile.production
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:80"